# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d577bb7464724e76e2b62daa39672fb"
name = "dev-remix-app"
handle = "dev-remix-app-2"
application_url = "https://represented-liver-alot-floors.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://represented-liver-alot-floors.trycloudflare.com/auth/callback",
  "https://represented-liver-alot-floors.trycloudflare.com/auth/shopify/callback",
  "https://represented-liver-alot-floors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://db84-61-193-58-237.ngrok-free.app/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "tsuzucle-checkout.myshopify.com"
automatically_update_urls_on_dev = true
